name: whitelist test

on:
  workflow_dispatch:
    inputs:
      org_slug:
        description: 'the slug of the github org to run against'
        type: string
        required: true
      token:
        description: 'github api token'
        type: string
        required: true

jobs:
  whitelist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: run
      run: dotnet run ${{ inputs.org_slug }} ${{ inputs.token }}